### Numpy ###

##### Arreglos #####

###### Importar la libreria ######

In [3]:
import numpy as np

###### Crear arreglo ######

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

###### Almacenar arreglo en una variable ######

In [4]:
a = np.array([1,2,3,4,5])

In [5]:
a

array([1, 2, 3, 4, 5])

###### Consultar tipo ######

In [6]:
type(a)

numpy.ndarray

###### Consultar atributos: cantidad de elementos. ######

In [7]:
a.size

5

###### Consultar atributos: cantidad de dimensiones. ######

In [8]:
a.ndim

1

###### Consultar atributos: tipos de datos que almacena. ######

In [9]:
a.dtype

dtype('int64')

###### Consultar atributos: conocer dimensiones y cantidad de elementos. ######

In [10]:
a.shape

(5,)

##### Operaciones #####

###### Sumar, restar, multiplicar y dividir sobre cada uno de los elementos ######

In [18]:
a = np.array([1,2,3,4,5])

In [13]:
a + 10

array([11, 12, 13, 14, 15])

In [14]:
a - 10

array([-9, -8, -7, -6, -5])

In [15]:
a * 10

array([10, 20, 30, 40, 50])

In [16]:
a / 10

array([0.1, 0.2, 0.3, 0.4, 0.5])

###### Sumar dos arreglos ######

In [17]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

a + b

array([ 7,  9, 11, 13, 15])

##### Tipos de datos #####

In [6]:
a = np.array([1,2,3,4,5])
a.dtype

dtype('int64')

In [18]:
a = np.array([1,2,3,4,5], dtype=float)
a

array([1., 2., 3., 4., 5.])

In [15]:
a = np.array([1,2,3,4,5], dtype=str)
a

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [16]:
a = np.array([1,2,3,4,5], dtype=bool)
a

array([ True,  True,  True,  True,  True])

In [17]:
a = np.array([1,2,3,4,5], dtype=np.complex_)
a

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

##### Crear arreglos #####

###### Arreglo con n cantidad de elementos ######

In [19]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

###### Opcionalmente un tercer argumento el cual denota la cantidad de saltos a utilizar ######

In [20]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Crear arreglo de ceros

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
np.zeros(10, dtype=int).dtype

dtype('int64')

###### Con 1(unos) ######

In [24]:
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

###### Crear Arreglo con valores basura ######

In [25]:
np.empty(10)

array([ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
        0.00000000e+000,  6.92810406e-310,  3.42346130e-032,
        4.90482501e-062,  7.42498991e-091,  1.68686412e-051,
       -1.38001728e+196])

In [26]:
np.empty(10, dtype=int)

array([                   0,                    0,                    0,
                          0,      140226387247104,  4136055101164970849,
        3689623894545806125,  3258410612596499554,  3847255202971399524,
       -1682198398138698394])

###### Crear arreglo con numeros enteros aleatorios ######

In [27]:
np.random.randint(0,100,50)

array([62, 13, 74, 76, 37, 41,  6, 20, 14, 35, 46, 18, 80, 70, 65, 79, 74,
       34,  2, 94, 56, 29, 40, 87, 67,  1, 99, 20, 90, 84, 81, 23, 42, 75,
       93, 26, 85, 20, 86,  7, 92, 84, 14, 61, 53, 46, 53, 69, 55, 49])

In [28]:
np.random.randint(0,10,50)

array([4, 3, 4, 3, 8, 0, 7, 1, 1, 7, 5, 6, 4, 8, 0, 1, 2, 3, 5, 5, 4, 4,
       4, 5, 9, 5, 0, 4, 4, 0, 2, 8, 3, 1, 0, 8, 0, 8, 7, 2, 6, 3, 8, 8,
       7, 5, 4, 9, 1, 1])

##### Obtener y actualizar elementos #####

###### Obtener un elemento (indice se cuenta a partir del 0 de izquierda a derecha) ######

In [32]:
a = np.random.randint(0,10,10)
a

array([6, 7, 3, 0, 1, 8, 0, 3, 8, 2])

In [33]:
a[0]

6

###### Si el indice es negativo se lee de derecha a izquierda  ######

In [34]:
a[-1]

2

###### Modificar valor de algun indice ######

In [35]:
a[0] = 100
a[0]

100

##### SubArreglos #####

In [36]:
a = np.random.randint(0,10,20)
a

array([8, 1, 8, 3, 8, 4, 5, 9, 8, 1, 1, 2, 8, 3, 8, 9, 7, 4, 3, 6])

###### a[start:end:saltos] ######

In [37]:
a[0:5]

array([8, 1, 8, 3, 8])

In [38]:
a[:5]

array([8, 1, 8, 3, 8])

In [39]:
a[5:]

array([4, 5, 9, 8, 1, 1, 2, 8, 3, 8, 9, 7, 4, 3, 6])

In [40]:
a[5::2]

array([4, 9, 1, 2, 3, 9, 4, 6])